planning_group: manipulator 
base_link:      base_link
tool_link:      tip
ee_link:        tool0

alpha_fis: "alpha_3c.fis"

joint_names:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

alpha_topic: "alpha"

max_fl: 0.831
min_fl: 0.169

add_object: false      # if true adds an obstacle defined in scene_objects.yaml
ws_boundaries: false   # if false does not consider workspace boundaries



